In [3]:
import numpy as np

In [41]:
array1=np.random.randint(3,19,size=(3,4,2)) #size=(blocks,rows of blocks,each row contains the columns)

In [43]:
array1

array([[[10,  3],
        [14,  5],
        [15, 15],
        [16, 13]],

       [[13, 14],
        [ 9,  5],
        [16,  8],
        [13, 15]],

       [[16, 12],
        [17,  3],
        [16,  7],
        [17, 10]]])

In [53]:
array1[1][1][1]

5

In [55]:
array2=np.array([1,3,4,5,6,6,7,8,10,15])

In [67]:
print(array2[1:4])

[3 4 5]


In [69]:
array3=np.random.randint(1,9,size=(3,4))

In [71]:
array3

array([[6, 8, 8, 1],
       [6, 1, 5, 7],
       [5, 8, 1, 8]])

In [83]:
array3[0:4,1:4]

array([[8, 8, 1],
       [1, 5, 7],
       [8, 1, 8]])

In [95]:
array3[1:4,2:3]

array([[5],
       [1]])